services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.1.4
    command: start-single-node --insecure
    ports:
      - "26257:26257"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.8.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      # --- Existing variables ---
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      # --- Add these two required variables ---
      - KAFKA_CFG_PROCESS_ROLES=broker  # Tells Kafka to run as a broker and use Zookeeper
      - KAFKA_CFG_NODE_ID=1            # Gives the broker a unique ID

volumes:
  cockroach-data: