version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.2
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=500m 