services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.2
    command: start-single-node --insecure
    ports:
      - "26257:26257"
    volumes:
      - cockroach-data:/cockroach/cockroach-data


volumes:
  cockroach-data:
