services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.1.4
    command: start-single-node --insecure
    ports:
      - "26257:26257"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.8.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_NODE_ID=1

  clickhouse-server:
    image: clickhouse/clickhouse-server:25.6-alpine
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default_db
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password

volumes:
  cockroach-data:
  clickhouse-data: