services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.1.4
    command: start-single-node --insecure
    ports:
      - "26257:26257"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.8.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      # Zookeeper connection
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

      # --- Combined listeners for internal and external traffic ---
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

      # Required for Zookeeper mode
      - ALLOW_PLAINTEXT_LISTENER=yes
      
  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'select release_version from system.local'"]
      interval: 15s
      timeout: 10s
      retries: 10

  clickhouse-server:
    image: clickhouse/clickhouse-server:25.6-alpine
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=log_data
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password

volumes:
  cockroach-data:
  cassandra-data:
  clickhouse-data: